import type { INodeProperties } from 'n8n-workflow';

export const leadOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['lead'],
			},
		},
		options: [
			{
				name: 'Convert to Loan',
				value: 'convert',
				description: 'Convert lead to loan',
				action: 'Convert lead to loan',
			},
			{
				name: 'Create',
				value: 'create',
				description: 'Create a new lead',
				action: 'Create a lead',
			},
			{
				name: 'Get',
				value: 'get',
				description: 'Get lead details',
				action: 'Get lead details',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Search many leads',
				action: 'Get many leads',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update lead',
				action: 'Update a lead',
			},
		],
		default: 'create',
	},
];

export const leadFields: INodeProperties[] = [
	// ----------------------------------
	//         lead:create
	// ----------------------------------
	{
		displayName: 'Assignee Email',
		name: 'assigneeEmail',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'Email of the primary lead owner',
	},
	{
		displayName: 'Loan Purpose',
		name: 'loanPurpose',
		type: 'options',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['create'],
			},
		},
		options: [
			{
				name: 'Purchase',
				value: 'Purchase',
			},
			{
				name: 'Refinance',
				value: 'Refinance',
			},
		],
		default: 'Purchase',
		description: 'Purpose of the loan',
	},
	{
		displayName: 'Borrower First Name',
		name: 'borrowerFirstName',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'First name of the primary borrower',
	},
	{
		displayName: 'Borrower Last Name',
		name: 'borrowerLastName',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'Last name of the primary borrower',
	},
	{
		displayName: 'Borrower Email',
		name: 'borrowerEmail',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['create'],
			},
		},
		default: '',
		description: 'Email address of the primary borrower',
	},
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['create'],
			},
		},
		options: [
			{
				displayName: 'Amortization Type',
				name: 'amortizationType',
				type: 'options',
				options: [
					{ name: 'Adjustable Rate', value: 'AdjustableRate' },
					{ name: 'Fixed', value: 'Fixed' },
				],
				default: 'Fixed',
				description: 'Type of amortization',
			},
			{
				displayName: 'Base Loan Amount',
				name: 'baseLoanAmount',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Borrower Annual Income',
				name: 'borrowerAnnualIncome',
				type: 'number',
				default: 0,
			},
			{
				displayName: 'Borrower Birth Date',
				name: 'borrowerBirthDate',
				type: 'string',
				default: '',
				description: 'Borrower birth date (YYYY-MM-DD)',
			},
			{
				displayName: 'Borrower Currently Owning Home',
				name: 'borrowerCurrentlyOwningAHome',
				type: 'boolean',
				default: false,
				description: 'Whether borrower currently owns a home',
			},
			{
				displayName: 'Borrower Email Opt Out',
				name: 'borrowerEmailOptOut',
				type: 'boolean',
				default: false,
				description: 'Whether borrower opted out of email',
			},
			{
				displayName: 'Borrower Employment Type',
				name: 'borrowerEmploymentType',
				type: 'options',
				options: [
					{ name: 'Active Military Duty', value: 'active military duty' },
					{ name: 'Employed', value: 'employed' },
					{ name: 'Other', value: 'other' },
					{ name: 'Retired', value: 'retired' },
					{ name: 'Self-Employed', value: 'self-employed' },
					{ name: 'Unemployed', value: 'unemployed' },
				],
				default: 'employed',
				description: 'Employment status of borrower',
			},
			{
				displayName: 'Borrower First Time Home Buyer',
				name: 'borrowerFirstTimeHomeBuyer',
				type: 'boolean',
				default: false,
				description: 'Whether borrower is a first-time homebuyer',
			},
			{
				displayName: 'Borrower Has Co-Borrower',
				name: 'borrowerHasCoBorrower',
				type: 'boolean',
				default: false,
				description: 'Whether there is a co-borrower',
			},
			{
				displayName: 'Borrower Has Real Estate',
				name: 'borrowerHasRealEstate',
				type: 'boolean',
				default: false,
				description: 'Whether borrower has real estate',
			},
			{
				displayName: 'Borrower Military Service Type',
				name: 'borrowerMilitaryServiceType',
				type: 'options',
				options: [
					{ name: 'Active Duty', value: 'ActiveDuty' },
					{ name: 'National Guard', value: 'NationalGuard' },
					{ name: 'Never Activated', value: 'NeverActivated' },
					{ name: 'Reserve', value: 'Reserve' },
					{ name: 'Veteran', value: 'Veteran' },
				],
				default: 'NeverActivated',
				description: 'Military service type',
			},
			{
				displayName: 'Borrower Mobile Phone',
				name: 'borrowerMobilePhone',
				type: 'string',
				default: '',
				description: 'Borrower mobile phone (10 digits)',
			},
			{
				displayName: 'Borrower Monthly Rent Amount',
				name: 'borrowerMonthlyRentAmt',
				type: 'string',
				default: '',
				description: 'Monthly rent amount',
			},
			{
				displayName: 'Borrower No Contact Request',
				name: 'borrowerNoContactRequest',
				type: 'boolean',
				default: false,
				description: 'Whether borrower requested no contact',
			},
			{
				displayName: 'Borrower Occupancy',
				name: 'borrowerOccupancy',
				type: 'options',
				options: [
					{ name: 'Living Rent Free', value: 'LivingRentFree' },
					{ name: 'Own', value: 'Own' },
					{ name: 'Rent', value: 'Rent' },
				],
				default: 'Rent',
				description: 'Current occupancy status',
			},
			{
				displayName: 'Borrower Planning To Sell Before Buying',
				name: 'borrowerPlanningToSellItBeforeBuying',
				type: 'boolean',
				default: false,
				description: 'Whether planning to sell current home before buying',
			},
			{
				displayName: 'Borrower Residence Duration (Months)',
				name: 'borrowerDurationMonthsCount',
				type: 'string',
				default: '',
				description: 'Address duration in months',
			},
			{
				displayName: 'Borrower Residence Duration (Years)',
				name: 'borrowerDurationYearsCount',
				type: 'string',
				default: '',
				description: 'Address duration in years',
			},
			{
				displayName: 'Borrower SMS Opt Out',
				name: 'borrowerSmsOptOut',
				type: 'boolean',
				default: false,
				description: 'Whether borrower opted out of SMS',
			},
			{
				displayName: 'Borrower SSN',
				name: 'borrowerSsn',
				type: 'string',
				default: '',
				description: 'Social security number',
			},
			{
				displayName: 'Borrower Total Liability',
				name: 'borrowerTotalLiability',
				type: 'number',
				default: 0,
				description: 'Total monthly liability',
			},
			{
				displayName: 'Borrower Years Since Bankruptcy',
				name: 'borrowerYearsSinceBankruptcy',
				type: 'string',
				default: '',
				description: 'Years since bankruptcy',
			},
			{
				displayName: 'Borrower Years Since Foreclosure',
				name: 'borrowerYearsSinceForeclosure',
				type: 'string',
				default: '',
				description: 'Years since foreclosure',
			},
			{
				displayName: 'Cashout Purpose',
				name: 'cashoutPurpose',
				type: 'options',
				options: [
					{ name: 'Debt Consolidation', value: 'DebtConsolidation' },
					{ name: 'Education', value: 'Education' },
					{ name: 'Home Improvement', value: 'HomeImprovement' },
					{ name: 'Interest Rate Reduction', value: 'InterestRateReductionOther' },
					{ name: 'Other', value: 'Other' },
				],
				default: 'DebtConsolidation',
				description: 'Purpose of cashout',
			},
			{
				displayName: 'Co-Borrower Birth Date',
				name: 'coBorrowerBirthDate',
				type: 'string',
				default: '',
				description: 'Co-borrower birth date (YYYY-MM-DD)',
			},
			{
				displayName: 'Co-Borrower Cell Phone',
				name: 'coBorrowerCellPhone',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Co-Borrower Email',
				name: 'coBorrowerEmail',
				type: 'string',
				default: '',
				description: 'Co-borrower email address',
			},
			{
				displayName: 'Co-Borrower First Name',
				name: 'coBorrowerFirstName',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Co-Borrower Last Name',
				name: 'coBorrowerLastName',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Co-Borrower Military Service Type',
				name: 'coBorrowerMilitaryServiceType',
				type: 'options',
				options: [
					{ name: 'Active Duty', value: 'ActiveDuty' },
					{ name: 'National Guard', value: 'NationalGuard' },
					{ name: 'Never Activated', value: 'NeverActivated' },
					{ name: 'Reserve', value: 'Reserve' },
					{ name: 'Veteran', value: 'Veteran' },
				],
				default: 'NeverActivated',
			},
			{
				displayName: 'Co-Borrower SSN',
				name: 'coBorrowerSsn',
				type: 'string',
				default: '',
				description: 'Co-borrower social security number',
			},
			{
				displayName: 'CRM Reference ID',
				name: 'crmReferenceId',
				type: 'string',
				default: '',
				description: 'External CRM reference identifier',
			},
			{
				displayName: 'Current Interest Rate (Refi)',
				name: 'currentInterestRateRefi',
				type: 'number',
				default: 0,
				description: 'Current interest rate for refinance',
			},
			{
				displayName: 'Desired Monthly Payment',
				name: 'desiredMonthlyPayment',
				type: 'number',
				default: 0,
				description: 'Desired monthly payment amount',
			},
			{
				displayName: 'Estimated Association Dues Monthly',
				name: 'estimatedAssociationDuesMonthly',
				type: 'string',
				default: '',
				description: 'Estimated monthly HOA dues',
			},
			{
				displayName: 'Estimated FICO',
				name: 'estimatedFICO',
				type: 'string',
				default: '',
				description: 'Estimated FICO score',
			},
			{
				displayName: 'Estimated HOI Monthly',
				name: 'estimatedHOIMonthly',
				type: 'string',
				default: '',
				description: 'Estimated monthly homeowners insurance',
			},
			{
				displayName: 'Estimated Property Taxes Monthly',
				name: 'estimatedPropertyTaxesMonthly',
				type: 'string',
				default: '',
				description: 'Estimated monthly property taxes',
			},
			{
				displayName: 'Homebuying Stage',
				name: 'homebuyingStage',
				type: 'options',
				options: [
					{ name: 'Found A House Or Offer Pending', value: 'FOUND_A_HOUSE_OR_OFFER_PENDING' },
					{ name: 'Getting Started', value: 'GETTING_STARTED' },
					{ name: 'Making Offers', value: 'MAKING_OFFERS' },
					{ name: 'Under Contract', value: 'UNDER_CONTRACT' },
				],
				default: 'GETTING_STARTED',
				description: 'Current stage in homebuying process',
			},
			{
				displayName: 'Impound Waiver',
				name: 'impoundWaiver',
				type: 'options',
				options: [
					{ name: 'All Waived', value: 'All Waived' },
					{ name: 'Hazard Insurance Waived', value: 'Hazard Insurance Waived' },
					{ name: 'None Waived', value: 'None Waived' },
					{ name: 'Property Taxes Waived', value: 'Property Taxes Waived' },
				],
				default: 'None Waived',
				description: 'Impound waiver status',
			},
			{
				displayName: 'Initial Adjustment Period (Months)',
				name: 'InitialFixedPeriodEffectiveMonthsCount',
				type: 'number',
				default: 0,
				description: 'Initial adjustment period in months',
			},
			{
				displayName: 'Interest Only',
				name: 'interestOnly',
				type: 'boolean',
				default: false,
				description: 'Whether loan is interest only',
			},
			{
				displayName: 'Interest Only Term (Months)',
				name: 'InterestOnlyTerm',
				type: 'number',
				default: 0,
				description: 'Interest only term in months',
			},
			{
				displayName: 'Lead Lost Reason',
				name: 'leadLostReason',
				type: 'options',
				options: [
					{ name: 'Decided To Wait', value: 'Decided_to_Wait' },
					{ name: 'Fake Email', value: 'Fake_Email' },
					{ name: 'Fake Number Email', value: 'Fake_Number_Email' },
					{ name: 'Fake Phone Number', value: 'Fake_Phone_Number' },
					{ name: 'Foreclosure Bankruptcy', value: 'Foreclosure_Bankruptcy' },
					{ name: 'Found Better Rate', value: 'Found_Better_Rate' },
					{ name: 'Found Lower Fees', value: 'Found_Lower_Fees' },
					{ name: 'House Fell Through', value: 'House_fell_through' },
					{ name: 'Income Too Low', value: 'Income_too_Low' },
					{ name: 'Not Interested', value: 'Not_Interested' },
					{ name: 'Not Licensed In State', value: 'Not_Licensed_in_State' },
					{ name: 'Other', value: 'Other' },
					{ name: 'Poor Credit', value: 'Poor_Credit' },
					{ name: 'Self Employed 1yr', value: 'Self_Employed_1yr' },
					{ name: 'Unresponsive', value: 'Unresponsive' },
				],
				default: 'Poor_Credit',
				description: 'Reason lead was lost',
			},
			{
				displayName: 'Lead Provided By',
				name: 'leadProvidedBy',
				type: 'string',
				default: '',
				description: 'Source that provided the lead',
			},
			{
				displayName: 'Lead Source',
				name: 'leadSource',
				type: 'string',
				default: '',
				description: 'Source of the lead',
			},
			{
				displayName: 'Lead Status',
				name: 'leadStatus',
				type: 'options',
				options: [
					{ name: 'Contacted', value: 'CONTACTED' },
					{ name: 'Lost', value: 'LOST' },
					{ name: 'New', value: 'NEW' },
					{ name: 'Qualified', value: 'QUALIFIED' },
				],
				default: 'NEW',
				description: 'Status of the lead',
			},
			{
				displayName: 'Lien Position',
				name: 'lienPosition',
				type: 'options',
				options: [
					{ name: 'First Lien', value: 'FirstLien' },
					{ name: 'Second Lien', value: 'SecondLien' },
				],
				default: 'FirstLien',
			},
			{
				displayName: 'Mortgage Type',
				name: 'mortgageType',
				type: 'options',
				options: [
					{ name: 'Conventional', value: 'Conventional' },
					{ name: 'FHA', value: 'FHA' },
					{ name: 'HELOAN', value: 'HELOAN' },
					{ name: 'HELOC', value: 'HELOC' },
					{ name: 'Non QM', value: 'NonQM' },
					{ name: 'Rural Development', value: 'RuralDevelopment' },
					{ name: 'USDA', value: 'USDA' },
					{ name: 'VA', value: 'VA' },
				],
				default: 'Conventional',
				description: 'Type of mortgage',
			},
			{
				displayName: 'Note Rate',
				name: 'noteRate',
				type: 'number',
				default: 0,
				description: 'Interest rate',
			},
			{
				displayName: 'Other Source Description',
				name: 'otherSourceDesc',
				type: 'string',
				default: '',
				description: 'Description if lead source is Other',
			},
			{
				displayName: 'Property City',
				name: 'propertyCity',
				type: 'string',
				default: '',
				description: 'Subject property city',
			},
			{
				displayName: 'Property County',
				name: 'propertyCounty',
				type: 'string',
				default: '',
				description: 'Subject property county',
			},
			{
				displayName: 'Property Postal Code',
				name: 'propertyPostalCode',
				type: 'string',
				default: '',
				description: 'Subject property postal code',
			},
			{
				displayName: 'Property State',
				name: 'propertyState',
				type: 'string',
				default: '',
				description: 'Subject property state',
			},
			{
				displayName: 'Property Street Address',
				name: 'propertyLineText',
				type: 'string',
				default: '',
				description: 'Subject property street address',
			},
			{
				displayName: 'Property Type',
				name: 'propertyType',
				type: 'options',
				options: [
					{ name: 'Co-Op (5-8 Stories)', value: 'COOP_5_8_STORIES' },
					{ name: 'Co-Op (Over 8 Stories)', value: 'COOP_OVER_8_STORIES' },
					{ name: 'Co-Op (Under 5 Stories)', value: 'COOP_UNDER_5_STORIES' },
					{ name: 'Condo (5-8 Stories)', value: 'CONDO_5_8_STORIES' },
					{ name: 'Condo (Over 8 Stories)', value: 'CONDO_OVER_8_STORIES' },
					{ name: 'Condo (Under 5 Stories)', value: 'CONDO_UNDER_5_STORIES' },
					{ name: 'Condotel', value: 'CONDOTEL' },
					{ name: 'Detached Condo', value: 'DETACHED_CONDO' },
					{ name: 'Four Unit', value: 'FOUR_UNIT' },
					{ name: 'Manufactured Double Wide', value: 'MANUFACTURED_DOUBLE_WIDE' },
					{ name: 'Manufactured Single Wide', value: 'MANUFACTURED_SINGLE_WIDE' },
					{ name: 'Mixed Use Property', value: 'MIXED_USE_PROPERTY' },
					{ name: 'PUD', value: 'PUD' },
					{ name: 'Single Family Attached', value: 'SINGLE_FAMILY_ATTACHED' },
					{ name: 'Single Family Detached', value: 'SINGLE_FAMILY_DETACHED' },
					{ name: 'Site Condo', value: 'SITE_CONDO' },
					{ name: 'Three Unit', value: 'THREE_UNIT' },
					{ name: 'Townhouse', value: 'TOWNHOUSE' },
					{ name: 'Two Unit', value: 'TWO_UNIT' },
					{ name: 'Vacant Lot / Land', value: 'VACANT_LOT_LAND' },
				],
				default: 'SINGLE_FAMILY_DETACHED',
				description: 'Type of property',
			},
			{
				displayName: 'Property Unit',
				name: 'propertyUnitId',
				type: 'string',
				default: '',
				description: 'Unit/apartment number',
			},
			{
				displayName: 'Property Usage Type',
				name: 'propertyUsageType',
				type: 'options',
				options: [
					{ name: 'Investment', value: 'Investment' },
					{ name: 'Primary Residence', value: 'PrimaryResidence' },
					{ name: 'Second Home', value: 'SecondHome' },
				],
				default: 'PrimaryResidence',
				description: 'How property will be used',
			},
			{
				displayName: 'Purchase Price / Estimated Value',
				name: 'purchasePriceOrEstimatedValue',
				type: 'number',
				default: 0,
				description: 'Purchase price or estimated property value',
			},
			{
				displayName: 'Qualifying Rate',
				name: 'qualifyingRate',
				type: 'number',
				default: 0,
				description: 'Qualifying interest rate',
			},
			{
				displayName: 'Refinance Type',
				name: 'refinanceType',
				type: 'options',
				options: [
					{ name: 'Cash Out', value: 'CashOut' },
					{ name: 'Limited Cash Out', value: 'LimitedCashOut' },
					{ name: 'No Cash Out', value: 'NoCashOut' },
				],
				default: 'NoCashOut',
				description: 'Type of refinance',
			},
			{
				displayName: 'Subject TBD Indicator',
				name: 'subjectTBDIndicator',
				type: 'boolean',
				default: false,
				description: 'Whether subject property is to be determined',
			},
			{
				displayName: 'Subsequent Adjustment Period (Months)',
				name: 'NormalRateAdjustmentPeriod',
				type: 'number',
				default: 0,
				description: 'Subsequent adjustment period in months',
			},
			{
				displayName: 'Term (Months)',
				name: 'term',
				type: 'number',
				default: 0,
				description: 'Amortization term in months',
			},
		],
	},

	// ----------------------------------
	//         lead:get
	// ----------------------------------
	{
		displayName: 'Lead ID',
		name: 'leadId',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['get'],
			},
		},
		default: '',
		description: 'The sysGUID of the lead to retrieve',
	},

	// ----------------------------------
	//         lead:getAll
	// ----------------------------------
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['getAll'],
			},
		},
		default: false,
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['getAll'],
				returnAll: [false],
			},
		},
		typeOptions: {
			minValue: 1,
			maxValue: 100,
		},
		default: 50,
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['getAll'],
			},
		},
		options: [
			{
				displayName: 'Lead Source',
				name: 'leadSource',
				type: 'string',
				default: '',
				description: 'Filter by lead source',
			},
			{
				displayName: 'Loan Purpose',
				name: 'loanPurpose',
				type: 'options',
				options: [
					{ name: 'Purchase', value: 'Purchase' },
					{ name: 'Refinance', value: 'Refinance' },
				],
				default: 'Purchase',
				description: 'Filter by loan purpose',
			},
			{
				displayName: 'Loan Type',
				name: 'loanType',
				type: 'options',
				options: [
					{ name: 'Conventional', value: 'Conventional' },
					{ name: 'FHA', value: 'FHA' },
					{ name: 'HELOAN', value: 'HELOAN' },
					{ name: 'HELOC', value: 'HELOC' },
					{ name: 'Non QM', value: 'NonQM' },
					{ name: 'Rural Development', value: 'RuralDevelopment' },
					{ name: 'USDA', value: 'USDA' },
					{ name: 'VA', value: 'VA' },
				],
				default: 'Conventional',
				description: 'Filter by loan type',
			},
			{
				displayName: 'Order By',
				name: 'orderBy',
				type: 'options',
				options: [
					{ name: 'Created At', value: 'createdAt' },
					{ name: 'Lead Status', value: 'leadStatus' },
					{ name: 'Loan Amount', value: 'loanAmount' },
					{ name: 'Updated At', value: 'updatedAt' },
				],
				default: 'createdAt',
				description: 'Field to order by',
			},
			{
				displayName: 'Sort Direction',
				name: 'sort',
				type: 'options',
				options: [
					{ name: 'Ascending', value: 'ASC' },
					{ name: 'Descending', value: 'DESC' },
				],
				default: 'DESC',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Contacted', value: 'CONTACTED' },
					{ name: 'Lost', value: 'LOST' },
					{ name: 'New', value: 'NEW' },
					{ name: 'Qualified', value: 'QUALIFIED' },
				],
				default: 'NEW',
				description: 'Filter by lead status',
			},
		],
	},

	// ----------------------------------
	//         lead:update
	// ----------------------------------
	{
		displayName: 'Lead ID',
		name: 'leadId',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['update'],
			},
		},
		default: '',
		description: 'The sysGUID of the lead to update',
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['update'],
			},
		},
		options: [
			{
				displayName: 'Assignee Email',
				name: 'assigneeEmail',
				type: 'string',
				default: '',
				description: 'Email of primary lead owner',
			},
			{
				displayName: 'Borrower First Name',
				name: 'borrowerFirstName',
				type: 'string',
				default: '',
				description: 'First name of the borrower',
			},
			{
				displayName: 'Borrower Last Name',
				name: 'borrowerLastName',
				type: 'string',
				default: '',
				description: 'Last name of the borrower',
			},
			{
				displayName: 'Borrower Email',
				name: 'borrowerEmail',
				type: 'string',
				default: '',
				description: 'Email address of the borrower',
			},
			{
				displayName: 'Homebuying Stage',
				name: 'homebuyingStage',
				type: 'options',
				options: [
					{ name: 'Found A House Or Offer Pending', value: 'FOUND_A_HOUSE_OR_OFFER_PENDING' },
					{ name: 'Getting Started', value: 'GETTING_STARTED' },
					{ name: 'Making Offers', value: 'MAKING_OFFERS' },
					{ name: 'Under Contract', value: 'UNDER_CONTRACT' },
				],
				default: 'GETTING_STARTED',
				description: 'Current homebuying stage',
			},
			{
				displayName: 'Lead Source',
				name: 'leadSource',
				type: 'string',
				default: '',
				description: 'Source of the lead',
			},
			{
				displayName: 'Lead Status',
				name: 'leadStatus',
				type: 'options',
				options: [
					{ name: 'Contacted', value: 'CONTACTED' },
					{ name: 'Lost', value: 'LOST' },
					{ name: 'New', value: 'NEW' },
					{ name: 'Qualified', value: 'QUALIFIED' },
				],
				default: 'NEW',
				description: 'Status of the lead',
			},
			{
				displayName: 'Loan Purpose',
				name: 'loanPurpose',
				type: 'options',
				options: [
					{ name: 'Purchase', value: 'Purchase' },
					{ name: 'Refinance', value: 'Refinance' },
				],
				default: 'Purchase',
				description: 'Purpose of the loan',
			},
			{
				displayName: 'Mortgage Type',
				name: 'mortgageType',
				type: 'options',
				options: [
					{ name: 'Conventional', value: 'Conventional' },
					{ name: 'FHA', value: 'FHA' },
					{ name: 'HELOAN', value: 'HELOAN' },
					{ name: 'HELOC', value: 'HELOC' },
					{ name: 'Non QM', value: 'NonQM' },
					{ name: 'Rural Development', value: 'RuralDevelopment' },
					{ name: 'USDA', value: 'USDA' },
					{ name: 'VA', value: 'VA' },
				],
				default: 'Conventional',
				description: 'Type of mortgage',
			},
		],
	},

	// ----------------------------------
	//         lead:convert
	// ----------------------------------
	{
		displayName: 'Lead ID',
		name: 'leadId',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['convert'],
			},
		},
		default: '',
		description: 'The sysGUID of the lead to convert',
	},
	{
		displayName: 'Loan Officer Email',
		name: 'loanOfficerEmail',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['lead'],
				operation: ['convert'],
			},
		},
		default: '',
		description: 'Email of the loan officer for the new loan',
	},
];
